name: admin-api
server:
  port: 8088
  tomcat.uri-encoding: UTF-8
db:
  url: jdbc:mysql://localhost:3306/vote?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: 123456
  
app:
  tokenExpirSeconds: 10
  
jsondoc:
  version: 1.0
  basePath: http://localhost:8080
  packages: 
    - com.example.controller
    - com.example.model
  playgroundEnabled: true
  displayMethodAs: URI  