insert into sys_user(username,password,salt,active) 
values('admin','VP_62BF8F958C8BCC37A15C4C9C69A20049','wqdszc',1);

INSERT INTO `sys_command` VALUES ('1', '0', '系统管理',  '', '1');
INSERT INTO `sys_command` VALUES ('2', '1', '用户管理',  'sys/userInfo.html', '1');
INSERT INTO `sys_command` VALUES ('3', '1', '角色管理',  'sys/roleManage.html', '1');
INSERT INTO `sys_command` VALUES ('4', '1', '权限管理',  'sys/authorization.html', '1');
INSERT INTO `sys_command` VALUES ('5', '1', '菜单管理',  'sys/menuList.html', '1');
INSERT INTO `sys_command` VALUES ('6', '0', '基础数据管理',  '', '1');
INSERT INTO `sys_command` VALUES ('7', '6', '小区管理',  'basis/uptownManage.html', '1');
INSERT INTO `sys_command` VALUES ('8', '6', '业主管理',  'basis/ownerManage.html', '1');
INSERT INTO `sys_command` VALUES ('9', '6', '房屋管理',  'basis/houseManage.html', '1');
INSERT INTO `sys_command` VALUES ('10', '6', '车位管理',  'basis/parkingLotManage.html', '1');
INSERT INTO `sys_command` VALUES ('11', '6', '家宴规格管理',  'basis/familySpecification.html', '1');
INSERT INTO `sys_command` VALUES ('12', '6', '家政规格管理',  'basis/housekeepingSpecification.html', '1');
INSERT INTO `sys_command` VALUES ('13', '6', '净菜规格管理',  '', '1');
INSERT INTO `sys_command` VALUES ('14', '6', '缴费项目管理',  'basis/paymentItem.html', '1');
INSERT INTO `sys_command` VALUES ('15', '6', '字典管理',  'basis/dictionaryManage.html', '1');
INSERT INTO `sys_command` VALUES ('16', '0', '物业服务',  '', '1');
INSERT INTO `sys_command` VALUES ('17', '16', '业主注册一览表',  '', '1');
INSERT INTO `sys_command` VALUES ('18', '16', '业主认证审批',  '', '1');
INSERT INTO `sys_command` VALUES ('19', '16', '物业缴费一览表',  '', '1');
INSERT INTO `sys_command` VALUES ('20', '16', '缴费记录查询',  '', '1');
INSERT INTO `sys_command` VALUES ('21', '16', '报事报修记录',  '', '1');
INSERT INTO `sys_command` VALUES ('22', '16', '投诉建议记录',  '', '1');
INSERT INTO `sys_command` VALUES ('23', '16', '物业公告发布',  '', '1');
INSERT INTO `sys_command` VALUES ('24', '16', '物业动态发布',  '', '1');
INSERT INTO `sys_command` VALUES ('25', '0', '商业服务',  '', '1');
INSERT INTO `sys_command` VALUES ('26', '25', '订单管理',  '', '1');
INSERT INTO `sys_command` VALUES ('27', '25', '广告位管理',  '', '1');
INSERT INTO `sys_command` VALUES ('28', '25', '周边商家信息',  '', '1');
INSERT INTO `sys_command` VALUES ('29', '25', '周边政务信息',  '', '1');