name: app-api
server:
  port: 8080
  tomcat.uri-encoding: UTF-8  
db:
  url: jdbc:mysql://localhost:3306/vote?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: 123456
  
app:
  tokenExpirSeconds: 10
  
